---
- hosts: web
  become: yes
  tasks:
   - name: Install httpd server
     yum: pkg=lynx state=latest
   - name: Querying for Telnet Install
     yum: pkg=telnet state=present update_cache=true

---
- hosts: web
  tasks:
  - name: obtain all ACM certificates
  aws_acm_facts:

- name: obtain all facts for a single ACM certificate
  aws_acm_facts:
    domain_name: "*.example_com"

- name: obtain all certificates pending validiation
  aws_acm_facts:
    statuses:
    - PENDING_VALIDATION